#\u6307\u5B9A\u670D\u52A1\u540D\u548C\u7AEF\u53E3
spring:
  application:
    name: gateway-zuul
server:
  port: 8001
  #\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

#\u96C6\u7FA4\u914D\u7F6E
zuul:
  routes:
    compute:
      path: /compute/**
      serviceId: ribbon