server:
  port: 9999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/root-wyj/springcloud_sc.git #
          search-paths: /cloud_config_properties

      label: master
      username: 997269684@qq.com
      password: wyj123456
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 开启 bus-refresh 端口
