server:
  port: 9999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/root-wyj/springcloud_sc.git #
          search-paths: /cloud_properties

      label: master
      username: *
      password: *

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

